# ./vendor/bin/ece-docker 'build:compose' --mode=developer --with-xdebug
version: '2.1'
services:
  db:
    hostname: db.fedex.local
    image: 'mariadb:10.6'
    shm_size: 2gb
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=magento2
    ports:
      - '3306'
    volumes:
      - '.:/app:delegated'
      - 'mymagento-magento-db:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -pmagento2'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - db.fedex.local
  redis:
    hostname: redis.fedex.local
    image: 'redis:7.0'
    volumes:
      - '.:/app:delegated'
    ports:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - redis.fedex.local
  rabbitmq:
    image: 'rabbitmq:latest'
    networks:
      magento:
        aliases:
          - rabbitmq.fedex.local
    ports:
      - '5672:5672'
      - '15672:15672'
  opensearch:
    hostname: opensearch.fedex.local
    image: 'magento/magento-cloud-docker-opensearch:2.4-1.3.7'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.seed_hosts=opensearch
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
    networks:
      magento:
        aliases:
          - opensearch.fedex.local
  fpm:
    hostname: fpm.fedex.local
    image: 'magento/magento-cloud-docker-php:8.2-fpm-1.4.0'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - fpm.fedex.local
    depends_on:
      db:
        condition: service_healthy
  web:
    hostname: web.fedex.local
    image: 'magento/magento-cloud-docker-nginx:1.24-1.3.7'
    extends: generic
    volumes:
      - '.:/app:delegated'
    environment:
      - WITH_XDEBUG=1
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
    ports:
      - '80:80'
      - '443:443'
    networks:
      magento:
        aliases:
          - web.fedex.local
    depends_on:
      fpm:
        condition: service_started
  fpm_xdebug:
    hostname: fpm_xdebug.fedex.local
    image: 'magento/magento-cloud-docker-php:8.2-fpm-1.4.0'
    extends: generic
    volumes:
      - '.:/app:delegated'
    environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium xdebug'
      - PHP_IDE_CONFIG=serverName=magento_cloud_docker
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9002 discover_client_host=1
    networks:
      magento:
        aliases:
          - fpm_xdebug.fedex.local
    depends_on:
      db:
        condition: service_started
  generic:
    hostname: generic.fedex.local
    image: 'magento/magento-cloud-docker-php:8.2-cli-1.4.0'
    env_file: ./.docker/config.env
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
  build:
    hostname: build.fedex.local
    image: 'magento/magento-cloud-docker-php:8.2-cli-1.4.0'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento-build:
        aliases:
          - build.fedex.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      opensearch:
        condition: service_healthy
  deploy:
    hostname: deploy.fedex.local
    image: 'magento/magento-cloud-docker-php:8.2-cli-1.4.0'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - deploy.fedex.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      opensearch:
        condition: service_healthy
volumes:
  mymagento-magento-db: {  }
networks:
  magento:
    driver: bridge
  magento-build:
    driver: bridge
